# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


TWILIO_ACCOUNT_SID: "AC4bb6fa4568260df672cbdb2389684bec"
TWILIO_AUTH_TOKEN: "97ea4ee4c5bfb09c0d3e2bfb36f0e4ef"

